version: "3"
services:
    nginx:
        image: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
   

    redis:
        container_name: redis
        hostname: redis
        image: redis
        ports:
          - 6379:6379

    database:
        container_name: mariadb
        image: mariadb
        environment:
          MYSQL_DATABASE: videoconference
          MYSQL_ROOT_PASSWORD: teamdnsb102
        ports:
         j - 3306:3306        
        volumes:
          - db-data:/var/lib/mysql


volumes:
    db-data: